In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [12]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
np.empty((4,5))

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 2.78149851e-307, 1.06811422e-306,
        9.34593493e-307, 1.33511290e-306],
       [1.33511969e-306, 1.78021527e-306, 1.29061142e-306,
        8.45599366e-307, 2.56765117e-312]])

In [23]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [24]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [25]:
np.linspace(2,6,1000)

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [29]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [30]:
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [31]:
np.logspace(2,4,10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [32]:
np.logspace(2,4,10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [2]:
a=np.arange(4,40).reshape(6,6)

In [42]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [45]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [44]:
a.min()

4

In [47]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [48]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [49]:
a/0

C:\Users\PRASHA~1\AppData\Local\Temp/ipykernel_7676/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [50]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [52]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [53]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]], dtype=int32)

In [3]:
b=np.array([2,3,1,2,3,2])

In [4]:
b

array([2, 3, 1, 2, 3, 2])

In [60]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [61]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [64]:
b=np.array([2,3,1,2,3,2])

In [65]:
b.T

array([2, 3, 1, 2, 3, 2])

In [66]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [67]:
b=b.reshape(1,-1)

In [68]:
b

array([[2, 3, 1, 2, 3, 2]])

In [70]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [5]:
a+b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [6]:
b.T+a

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [7]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [8]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [9]:
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [10]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [11]:
x=np.array([1,2,3])

In [12]:
y=x
#shallow copy

In [13]:
y

array([1, 2, 3])

In [14]:
z=np.copy(x)
#deep copy

In [15]:
z

array([1, 2, 3])

In [16]:
x[0]=100

In [17]:
y

array([100,   2,   3])

In [18]:
z

array([1, 2, 3])

In [19]:
id(z)

1479930592400

In [20]:
id(y)

1479930592016

In [21]:
id(x)

1479930592016

In [22]:
x

array([100,   2,   3])

In [23]:
id(x[0])

1479930623312

In [24]:
y

array([100,   2,   3])

In [25]:
id(y[0])

1479930623504

In [26]:
id(x[1])

1479930622352

In [27]:
id(y[1])

1479930623792

In [28]:
x-np.array([1,2,3])

array([99,  0,  0])

In [29]:
y=x

In [30]:
id(x)

1479930592016

In [31]:
id(y)

1479930592016

In [32]:
id(x[0])

1479930624080

In [33]:
id(y[0])

1479930623888

In [2]:
su=np.array([567,345])

In [6]:
df=su

In [36]:
id(su)

1479930592688

In [37]:
id(df)

1479930592688

In [38]:
id(su[0])

1479930624496

In [39]:
id(df[0])

1479930624464

In [7]:
id(su[0])==id(df[0])

True

In [8]:
id(su[1])==id(df[0])

True

In [3]:
c="sudh"

In [4]:
id(c)

2499421922800

In [5]:
id(c)==id(su)

False